# Generated by Django 3.2.13 on 2022-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('kode_cabang', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nama_cabang', models.CharField(max_length=255)),
                ('email_cabang', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cabang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('kode_cabang', models.CharField(max_length=255, unique=True)),
                ('kode_produk', models.CharField(max_length=255, unique=True)),
                ('jumlah_pembelian', models.IntegerField()),
                ('harga_satuan', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('tanggal_transaksi', models.DateField()),
            ],
            options={
                'db_table': 'detail_transaksi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KodeProduk',
            fields=[
                ('kode_produk', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kode_produk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shcedule',
            fields=[
                ('id_job', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_eksekusi', models.DateField(blank=True, null=True)),
                ('jam_eksekusi', models.TimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'shcedule',
                'managed': False,
            },
        ),
    ]
