# Generated by Django 3.2.13 on 2022-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
    ]
