# Generated by Django 3.2.13 on 2022-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Running',
            fields=[
                ('idRunning', models.AutoField(primary_key=True, serialize=False)),
                ('running_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kode_produk',
                'managed': False,
            },
        ),
    ]
