# Generated by Django 3.2.13 on 2022-06-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0003_running'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='running',
            table='running',
        ),
    ]
