# Generated by Django 3.2.13 on 2022-06-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0005_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False},
        ),
    ]
