# Generated by Django 3.2.13 on 2022-06-20 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0006_alter_login_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='login_admin',
        ),
    ]
