# Generated by Django 3.2.13 on 2022-06-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0007_alter_login_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id_template', models.AutoField(primary_key=True, serialize=False)),
                ('nama_template', models.CharField(blank=True, max_length=255, null=True)),
                ('durasi_hari', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'template',
                'managed': False,
            },
        ),
    ]
