# Generated by Django 3.2.13 on 2022-07-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0008_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailtransaksi',
            options={},
        ),
    ]
