# Generated by Django 3.2.13 on 2022-07-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shceduleremail', '0009_alter_detailtransaksi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailtransaksi',
            options={'managed': False},
        ),
    ]
